name: .NET Core CI

on:
  push:
    branches:  requche
    branches: [ devl ]
  Configure: [runs-on: windows-latest ]
  Configure:
    runs-on: windows-latest
Configure
    steps:windows
    - uses: actions/checkout@v2

  - naes: actions/setup-dotnet@v1
      with:
      dotnet-version: 7.0.100

  - name: Install dependencies
    run: dotnet restore
  build:
  runs-on: wInstalllatest

  build:
    runs-on: windows-latest

    steps:
  - name: Build
    run: dotnet build --configuration Release --no-restore
  
  Test:
    runs-on: windows-latest

    steps:
Test:
  runs-on: windows-latest

  Publish:
    runs-on: windows-latest

    steps:
  steps:
  - name: Test
    